"""
Create Python Greeting Function

Create a Python function called greet_user that takes a name parameter and returns a personalized greeting message. Include a docstring and type hints.

Auto-generated by Autonomous Development Pipeline
"""

def greet_user(name: str) -> str:
    """
    Generate a personalized greeting message.
    
    Args:
        name: The name of the person to greet
        
    Returns:
        str: A personalized greeting message
    """
    return f"Hello, {name}! Welcome to our application."


# Example usage
if __name__ == "__main__":
    # Test the function
    test_names = ["Alice", "Bob", "Charlie"]
    for name in test_names:
        print(greet_user(name))
