apiVersion: v1
kind: Service
metadata:
  name: haiku-postgres-primary
  namespace: haiku-battle
  labels:
    app.kubernetes.io/component: postgres-primary
spec:
  selector:
    app.kubernetes.io/component: postgres-primary
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
